export const REGIONALES_PUERTOS_DEFAULT = [
  'BUENAVENTURA',
  'MUELLES CONTECAR',
  'BARRANQUILLA PUERTO',
  'BOGOTÁ',
  'SPRC CARTAGENA',
];

export const INSPECTORES_PUERTOS_DEFAULT = ['Inspector Demo 1', 'Inspector Demo 2'];

export const EMPAQUES_PUERTOS_DEFAULT = [
  'CONTENEDOR DE 40 PIES',
  "CONTENEDOR X 40' OPEN TOP",
  'PALLET',
  'CAJA DE CARTÓN',
  'CARGA SUELTA',
];

export const TIPOS_AVERIA_PUERTOS_DEFAULT = [
  'ABOLLADURAS',
  'ROTURA',
  'HUMEDAD',
  'FALTANTE',
  'OTRO',
];

export const TIPOS_INSPECCION_PUERTOS_DEFAULT = [
  'INSPECCIÓN DIAN',
  'PREINSPECCIÓN',
  'PREINSPECCIÓN NOVEDAD',
  'INSPECCIÓN',
];

export const TIPOS_TRANSPORTE_PUERTOS_DEFAULT = ['MARÍTIMO', 'AÉREO', 'TERRESTRE', 'MULTIMODAL'];

export const TIPOS_MERCANCIA_PUERTOS_DEFAULT = [
  'ROPA DEPORTIVA',
  'ZAPATOS DEPORTIVOS',
  'ACCESORIOS DEPORTIVOS',
  'BALONES Y EQUIPAMIENTO',
  'BOLSOS Y MOCHILAS',
  'GORRAS Y SOMBREROS',
  'CALCETINES Y MEDIAS',
  'ROPA DE ENTRENAMIENTO',
  'ROPA DE FÚTBOL',
  'ROPA DE RUNNING',
  'ROPA OUTDOOR',
  'CALZADO LIFESTYLE / ORIGINALS',
  'MATERIAL PROMOCIONAL / DISPLAY',
  'MIXTO (VARIAS CATEGORÍAS)',
  'OTRO',
];

export const ASEGURADORAS_PUERTOS_DEFAULT = ['SURA', 'MAPFRE', 'LIBERTY', 'BOLÍVAR'];

export const SUCURSALES_PUERTOS_DEFAULT = ['Bogotá', 'Medellín', 'Cali', 'Barranquilla'];

export const ESTADOS_ACTA_PUERTOS_DEFAULT = ['Activo', 'Cerrado', 'Borrador'];

export const DEFAULTS_POR_TIPO = {
  regional: REGIONALES_PUERTOS_DEFAULT,
  inspector: INSPECTORES_PUERTOS_DEFAULT,
  empaque: EMPAQUES_PUERTOS_DEFAULT,
  tipo_averia: TIPOS_AVERIA_PUERTOS_DEFAULT,
  tipo_inspeccion: TIPOS_INSPECCION_PUERTOS_DEFAULT,
  tipo_transporte: TIPOS_TRANSPORTE_PUERTOS_DEFAULT,
  tipo_mercancia: TIPOS_MERCANCIA_PUERTOS_DEFAULT,
  aseguradora: ASEGURADORAS_PUERTOS_DEFAULT,
  sucursal: SUCURSALES_PUERTOS_DEFAULT,
  estado_acta: ESTADOS_ACTA_PUERTOS_DEFAULT,
};
