export const REGIONALES_PUERTOS_DEFAULT = [
  'BUENAVENTURA',
  'MUELLES CONTECAR',
  'BARRANQUILLA PUERTO',
  'BOGOTÁ',
  'SPRC CARTAGENA',
];

export const INSPECTORES_PUERTOS_DEFAULT = ['Inspector Demo 1', 'Inspector Demo 2'];

export const EMPAQUES_PUERTOS_DEFAULT = [
  'CONTENEDOR DE 40 PIES',
  "CONTENEDOR X 40' OPEN TOP",
  'PALLET',
  'CAJA DE CARTÓN',
  'CARGA SUELTA',
];

export const TIPOS_AVERIA_PUERTOS_DEFAULT = [
  'ABOLLADURAS',
  'ROTURA',
  'HUMEDAD',
  'FALTANTE',
  'OTRO',
];

export const TIPOS_INSPECCION_PUERTOS_DEFAULT = [
  'INSPECCIÓN DIAN',
  'PREINSPECCIÓN',
  'PREINSPECCIÓN NOVEDAD',
  'INSPECCIÓN',
];

export const TIPOS_TRANSPORTE_PUERTOS_DEFAULT = ['MARÍTIMO', 'AÉREO', 'TERRESTRE', 'MULTIMODAL'];

export const TIPOS_MERCANCIA_PUERTOS_DEFAULT = [
  'ROPA DEPORTIVA',
  'ZAPATOS DEPORTIVOS',
  'ACCESORIOS DEPORTIVOS',
  'BALONES Y EQUIPAMIENTO',
  'BOLSOS Y MOCHILAS',
  'GORRAS Y SOMBREROS',
  'CALCETINES Y MEDIAS',
  'ROPA DE ENTRENAMIENTO',
  'ROPA DE FÚTBOL',
  'ROPA DE RUNNING',
  'ROPA OUTDOOR',
  'CALZADO LIFESTYLE / ORIGINALS',
  'MATERIAL PROMOCIONAL / DISPLAY',
  'MIXTO (VARIAS CATEGORÍAS)',
  'OTRO',
];

export const ASEGURADORAS_PUERTOS_DEFAULT = [
  'ACI CARGO',
  'ADIDAS COLOMBIA',
  'ALLIANZ SEGUROS S. A.',
  'BBVA SEGUROS',
  'CHUBB DE COLOMBIA',
  'LIBERTY',
  'MAPFRE SEGUROS',
  'SBS SEGUROS',
  'SEGUROS BOLIVAR S.A',
  'SERVICIOS BOLIVAR',
  'SURA',
];

/** Vacío a propósito: los asegurados se agregan desde Catálogos según cada operación. */
export const ASEGURADOS_PUERTOS_DEFAULT = [];

/**
 * Sucursales extraídas de capturas de operación (Aseguradora → Sucursal).
 * Se cargan con seed; el UI filtra por marca de aseguradora.
 */
export const SUCURSALES_PUERTOS_DEFAULT = [
  // ACI CARGO
  'ACI CARGO B/QUILLA',
  // ADIDAS COLOMBIA
  'ADIDAS',
  // ALLIANZ
  'ALLIANZ SEGUROS S.A. SUC MEDELLIN',
  // BBVA
  'BBVA - BOGOTA',
  // CHUBB
  'CHUBB SUC BARRANQUILLA',
  'CHUBB SUC BOGOTA',
  'CHUBB SUC CALI',
  'CHUBB SUC MEDELLIN',
  // SBS
  'SBS B/quilla',
  // SERVICIOS BOLIVAR
  'ASISTENCIA BOGOTA',
  // SEGUROS BOLIVAR
  'BOLIVAR -BOGOTA',
  'BOLIVAR B/QUILLA',
  'BOLIVAR CARTAGENA',
  'BOLIVAR CORREDORES',
  'BOLIVAR MEDELLIN',
  'SEGUROS BOLIVAR - LEASING BOLIVAR',
  'SEGUROS BOLIVAR MANIZALES',
  'Sucursal Pereira',
  // MAPFRE (lista de capturas)
  'ANTIOQUIA',
  'BOGOTA I',
  'BOGOTA II',
  'DIRECTO',
  'GUARNE',
  'LA ESTRELLA',
  'MANIZALES',
  'MAPFRE - YUMBO',
  'MAPFRE AGUSTIN CODAZZI',
  'MAPFRE ARMENIA',
  'MAPFRE CHIA',
  'MAPFRE ITAGUI',
  'MAPFRE MONTERIA',
  'MAPFRE PRINCIPAL',
  'MAPFRE RIO NEGRO',
  'MAPFRE RIOHACHA',
  'MAPFRE SEGUROS - AV. 82 BOGOTA',
  'MAPFRE SEGUROS - AVENIDA CHILE',
  'MAPFRE SEGUROS - BUCARAMANGA',
  'MAPFRE SEGUROS - CABECERA LLANO',
  'MAPFRE SEGUROS - CARTAGENA',
  'MAPFRE SEGUROS - CHICO',
  'MAPFRE SEGUROS - FONTIBON',
  'MAPFRE SEGUROS - HEROES',
  'MAPFRE SEGUROS - IBAGUE',
  'MAPFRE SEGUROS - LISBOA',
  'MAPFRE SEGUROS - MARLY',
  'MAPFRE SEGUROS - NOGAL',
  'MAPFRE SEGUROS - PEPE SIERRA',
  'MAPFRE SEGUROS - PEREIRA',
  'MAPFRE SEGUROS - QUINTA PAREDES',
  'MAPFRE SEGUROS - ROSALES',
  'MAPFRE SEGUROS - SAN DIEGO',
  'MAPFRE SEGUROS - SANTA BARBARA',
  'MAPFRE-MEDELLIN',
  'MAPFRE/ CASTELLANA',
  'MAPFRE/BQUILLA',
  'MAPFRE/CORREDORES',
  'MAPFRE/SALITRE PLAZA',
  'REG.CORREDORES CALI',
  'REG.CUENTAS CORPORATIV.BOGOTA',
  'REG.EJE CAFETERO',
  'REG.NORTE B/QUILLA',
  'REG.OCCIDENTE',
];

export const ESTADOS_ACTA_PUERTOS_DEFAULT = ['Activo', 'Cerrado', 'Borrador'];

export const DEFAULTS_POR_TIPO = {
  regional: REGIONALES_PUERTOS_DEFAULT,
  inspector: INSPECTORES_PUERTOS_DEFAULT,
  empaque: EMPAQUES_PUERTOS_DEFAULT,
  tipo_averia: TIPOS_AVERIA_PUERTOS_DEFAULT,
  tipo_inspeccion: TIPOS_INSPECCION_PUERTOS_DEFAULT,
  tipo_transporte: TIPOS_TRANSPORTE_PUERTOS_DEFAULT,
  tipo_mercancia: TIPOS_MERCANCIA_PUERTOS_DEFAULT,
  aseguradora: ASEGURADORAS_PUERTOS_DEFAULT,
  asegurado: ASEGURADOS_PUERTOS_DEFAULT,
  sucursal: SUCURSALES_PUERTOS_DEFAULT,
  estado_acta: ESTADOS_ACTA_PUERTOS_DEFAULT,
};
